spring:
  jpa:
    show-sql: false
    
  security:
    user:
      password: secret

    oauth2:
      client:
        registration:
          google:
            client-id: 592478762979-m9jq555btrtq30hvdbn7h9uc8evarbd7.apps.googleusercontent.com
            client-secret: bI3VLaBK3Jx3jSwZNNiuiswN
logging:
  level:
    org.springframework.security: DEBUG
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
appli:
  jwt:
    secretKey: secret
    validity: 1000
    rememberMe: 1000
    
