spring:
  jpa:
    show-sql: false
    
  security:
    user:
      password: secret

    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
logging:
  level:
    org.springframework.security: DEBUG
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
appli:
  jwt:
    secretKey: secret
    validity: 1000
    rememberMe: 1000
    
